server:
  port: 8081

spring:
  application:
    name: patient-service
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:54322/postgres}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health
