server:
  port: 8080

spring:
  application:
    name: gateway-service

  # Gateway uses reactive web, not MVC
  main:
    web-application-type: reactive

  # Gateway doesn't need database - disable auto-configuration
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health