# Healthcare AI Microservices - Docker Compose Template
# Local development environment
#
# Copy this file to docker-compose.yml and configure with your actual values
# docker-compose.yml is gitignored and should NOT be committed

# Database connection configuration:
# - Uses environment variables for sensitive credentials
# - Configure SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME, SPRING_DATASOURCE_PASSWORD
# - Network mode: host (required for external database connections)

version: '3.8'

services:
  # Patient Service
  patient-service:
    build:
      context: ../
      dockerfile: services/patient-service/Dockerfile
    container_name: healthcare-patient-service
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      SPRING_JPA_HIBERNATE_DDL_AUTO: none

networks:
  healthcare-network:
    driver: bridge
