package com.healthcare.entity;

import com.healthcare.constants.AppConstants;
import com.healthcare.constants.DatabaseConstants;
import com.healthcare.utils.ValidationUtils;
import jakarta.persistence.Column;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;

import java.time.OffsetDateTime;
import java.util.UUID;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * Base entity providing common audit fields for all healthcare entities.
 *
 * Fields managed automatically:
 * - id         — UUID primary key, generated by the database
 * - createdAt  — set once on INSERT, never updated
 * - updatedAt  — updated on every UPDATE
 * - updatedBy  — set by service layer from JWT context; falls back to "system"
 *
 * NOTE: AuditListener is a static inner class and cannot @Autowire Spring beans.
 * The service layer is responsible for calling entity.setUpdatedBy(username)
 * before saving whenever a real user context is available.
 */
@MappedSuperclass
@EntityListeners(BaseEntity.AuditListener.class)
public abstract class BaseEntity {

    /**
     * UUID primary key. Generated by the database via gen_random_uuid().
     * Immutable after creation.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = DatabaseConstants.COL_ID,
            updatable = false,
            nullable = false,
            columnDefinition = "UUID DEFAULT gen_random_uuid()")
    private UUID id;

    /**
     * Timestamp when this record was first created.
     * Set by Hibernate on INSERT; never updated.
     */
    @CreationTimestamp
    @Column(name = DatabaseConstants.COL_CREATED_AT,
            nullable = false,
            updatable = false,
            columnDefinition = DatabaseConstants.COLUMN_DEFINITION_TIMESTAMPTZ)
    private OffsetDateTime createdAt;

    /**
     * Timestamp when this record was last modified.
     * Updated by Hibernate on every UPDATE.
     */
    @UpdateTimestamp
    @Column(name = DatabaseConstants.COL_UPDATED_AT,
            nullable = false,
            columnDefinition = DatabaseConstants.COLUMN_DEFINITION_TIMESTAMPTZ)
    private OffsetDateTime updatedAt;

    /**
     * Username or system identifier of who last modified this record.
     * Set by the service layer from JWT claims.
     * Defaults to "system" if no user context is available (e.g. during registration).
     */
    @Column(name = DatabaseConstants.COL_UPDATED_BY, length = 100, nullable = false)
    private String updatedBy;

    // ------------------------------------------------------------------
    // Constructor
    // ------------------------------------------------------------------

    protected BaseEntity() {}

    // ------------------------------------------------------------------
    // Getters (all read-only from outside — no setters for id/createdAt)
    // ------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    // ------------------------------------------------------------------
    // Setter — only updatedBy is settable externally
    // ------------------------------------------------------------------

    /**
     * Set the identifier of the user who last modified this entity.
     * Call this in the service layer with the username extracted from JWT.
     * Example: entity.setUpdatedBy(jwtClaims.getUsername());
     *
     * @param updatedBy username from JWT, or "system" for automated operations
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = ValidationUtils.validateRequiredString(
                updatedBy, "Updated by", 100);
    }

    // ------------------------------------------------------------------
    // JPA Audit Listener
    // ------------------------------------------------------------------

    /**
     * Automatically sets updatedBy to "system" before INSERT or UPDATE
     * if the service layer has not already set it.
     *
     * For authenticated requests, the service layer should always call
     * entity.setUpdatedBy(username) before saving — this is the fallback only.
     */
    public static class AuditListener {

        @PrePersist
        public void prePersist(BaseEntity entity) {
            if (entity.getUpdatedBy() == null || entity.getUpdatedBy().isBlank()) {
                entity.setUpdatedBy(AppConstants.SYSTEM_USER);
            }
        }

        @PreUpdate
        public void preUpdate(BaseEntity entity) {
            if (entity.getUpdatedBy() == null || entity.getUpdatedBy().isBlank()) {
                entity.setUpdatedBy(AppConstants.SYSTEM_USER);
            }
        }
    }
}