package com.healthcare.entity;

import com.healthcare.constants.DatabaseConstants;
import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

import java.util.UUID;

/**
 * Extends BaseEntity with an auto-generated UUID primary key.
 *
 * Extended by all entities that have a single UUID PK managed by the database:
 *   User, Patient, Provider, Organization, Encounter, AuditLog
 *
 * Entities with composite PKs (Condition, Allergy) extend BaseEntity directly
 * and define their own @EmbeddedId.
 */
@MappedSuperclass
public abstract class ProfileBaseEntity extends BaseEntity {

    /**
     * Auto-generated UUID primary key.
     * Generated by the database via gen_random_uuid().
     * Immutable after creation.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = DatabaseConstants.COL_ID,
            updatable = false,
            nullable = false,
            columnDefinition = "UUID DEFAULT gen_random_uuid()")
    private UUID id;

    // ------------------------------------------------------------------
    // Constructor
    // ------------------------------------------------------------------

    protected ProfileBaseEntity() {}

    // ------------------------------------------------------------------
    // Getter — no setter, id is immutable
    // ------------------------------------------------------------------

    public UUID getId() { return id; }
}