package com.healthcare.entity;

import com.healthcare.constants.AppConstants;
import com.healthcare.constants.DatabaseConstants;
import com.healthcare.constants.ValidationConstants;
import com.healthcare.constants.ValidationPatterns;
import com.healthcare.enums.Gender;
import com.healthcare.exception.ValidationException;
import com.healthcare.utils.ValidationUtils;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

import java.util.UUID;

/**
 * Provider entity mapping to the providers table.
 *
 * Registration flow:
 *   1. Admin creates provider record → provider_code auto-generated
 *   2. Admin gives provider_code to provider
 *   3. Provider registers with provider_code + name
 *
 * Trimming and business validation belongs in the service layer.
 * Entity only checks structural requirements.
 */
@Entity
@Table(name = DatabaseConstants.TABLE_PROVIDERS,
       indexes = {
           @Index(name = DatabaseConstants.INDEX_PROVIDERS_ORGANIZATION,
                  columnList = DatabaseConstants.COL_ORGANIZATION_ID),
           @Index(name = DatabaseConstants.INDEX_PROVIDERS_AUTH_ID,
                  columnList = DatabaseConstants.COL_AUTH_ID),
           @Index(name = DatabaseConstants.INDEX_PROVIDERS_SPECIALITY,
                  columnList = DatabaseConstants.COL_SPECIALITY),
           @Index(name = DatabaseConstants.INDEX_PROVIDERS_CODE,
                  columnList = DatabaseConstants.COL_PROVIDER_CODE),
           @Index(name = DatabaseConstants.INDEX_PROVIDERS_ACTIVE,
                  columnList = DatabaseConstants.COL_IS_ACTIVE)
       })
public class Provider extends ProfileBaseEntity {

    private static final String FIELD_PROVIDER_NAME  = "Provider name";
    private static final String FIELD_LICENSE_NUMBER  = "License number";
    private static final String FIELD_PHONE = "Phone";
    private static final String FIELD_ORGANIZATION_ID = "Organization ID";

    // ------------------------------------------------------------------
    // Synthea fields
    // ------------------------------------------------------------------

    @Column(name = DatabaseConstants.COL_ORGANIZATION_ID)
    private UUID organizationId;

    @Size(max = DatabaseConstants.LEN_PROVIDER_NAME)
    @Column(name = DatabaseConstants.COL_NAME)
    private String name;

    @Enumerated(EnumType.STRING)
    @Column(name = DatabaseConstants.COL_GENDER)
    private Gender gender;

    @Size(max = DatabaseConstants.LEN_SPECIALITY)
    @Column(name = DatabaseConstants.COL_SPECIALITY)
    private String speciality;

    /** Synthea metric - number of encounters recorded. */
    @Column(name = DatabaseConstants.COL_ENCOUNTERS)
    private Integer encounters;

    /** Synthea metric - number of procedures recorded. */
    @Column(name = DatabaseConstants.COL_PROCEDURES)
    private Integer procedures;

    // ------------------------------------------------------------------
    // Application fields
    // ------------------------------------------------------------------

    /**
     * Links to users.id after provider registers an account.
     * Null until registration is complete.
     */
    @Column(name = DatabaseConstants.COL_AUTH_ID, unique = true)
    private UUID authId;

    /**
     * Provider code — auto-generated by DB sequence.
     * Format: PRV-000001.
     * Used for provider registration: provider_code + name must match.
     */
    @Size(max = DatabaseConstants.LEN_PROVIDER_CODE)
    @Column(name = DatabaseConstants.COL_PROVIDER_CODE, unique = true)
    private String providerCode;

    @Size(max = DatabaseConstants.LEN_PHONE)
    @Pattern(regexp = ValidationPatterns.PHONE,
             message = "Phone must be a valid international format")
    @Column(name = DatabaseConstants.COL_PHONE)
    private String phone;

    @Size(max = DatabaseConstants.LEN_LICENSE_NUMBER)
    @Column(name = DatabaseConstants.COL_LICENSE_NUMBER)
    private String licenseNumber;

    /**
     * NPI (National Provider Identifier) — 10-digit federal CMS identifier.
     * Set during provider onboarding, not during auth registration.
     */
    @Size(max = DatabaseConstants.LEN_NPI)
    @Pattern(regexp = ValidationPatterns.NPI, message = "NPI must be a 10-digit number")
    @Column(name = DatabaseConstants.COL_NPI_NUMBER, unique = true)
    private String npi;

    @Column(name = DatabaseConstants.COL_IS_ACTIVE)
    private Boolean isActive = true;

    @Column(name = DatabaseConstants.COL_BIO,
            columnDefinition = DatabaseConstants.COLUMN_DEFINITION_TEXT)
    private String bio;

    // ------------------------------------------------------------------
    // JPA relationships
    // ------------------------------------------------------------------

    /**
     * Navigation to the linked organization.
     * insertable/updatable = false — organizationId column manages the FK.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = DatabaseConstants.COL_ORGANIZATION_ID,
                insertable = false, updatable = false)
    private Organization organization;

    /**
     * Navigation to the linked user account.
     * Null until provider completes registration.
     * insertable/updatable = false — authId column manages the FK.
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = DatabaseConstants.COL_AUTH_ID,
                insertable = false, updatable = false)
    private User user;

    // ------------------------------------------------------------------
    // Constructors
    // ------------------------------------------------------------------

    /** For JPA only. */
    @SuppressWarnings(AppConstants.SUPPRESS_UNUSED)
    protected Provider() {}

    /**
     * Minimal constructor for API-created provider records.
     *
     * @param organizationId the organization this provider belongs to
     * @param name           provider full name
     */
    public Provider(UUID organizationId, String name) {
        if (organizationId == null)
            throw new ValidationException(FIELD_ORGANIZATION_ID + " is required");
        if (name == null || name.isBlank())
            throw new ValidationException(FIELD_PROVIDER_NAME + " is required");

        this.organizationId = organizationId;
        this.name           = name.trim();
        this.isActive       = true;
    }

    // ------------------------------------------------------------------
    // Business methods
    // ------------------------------------------------------------------

    /**
     * Whether this provider has registered an account.
     */
    public boolean isRegistered() {
        return authId != null;
    }

    /**
     * Link this provider record to a user account after successful registration.
     * Can only be set once — cannot re-link to a different user.
     *
     * @param userId the UUID from users.id
     */
    public void linkAuthAccount(UUID userId) {
        if (userId == null)
            throw new ValidationException("User ID cannot be null");
        if (this.authId != null)
            throw new ValidationException("Provider is already linked to an account");
        this.authId = userId;
    }

    /**
     * Validate registration credentials.
     * Provider must provide provider_code + name to register.
     *
     * @param providerCode provided provider code
     * @param name         provided name
     * @return true if credentials match this provider record
     */
    public boolean matchesRegistrationCredentials(String providerCode, String name) {
        if (providerCode == null || name == null)
            return false;
        return this.providerCode.equalsIgnoreCase(providerCode)
                && this.name.equalsIgnoreCase(name.trim());
    }

    public boolean isActive() {
        return Boolean.TRUE.equals(isActive);
    }

    // ------------------------------------------------------------------
    // Getters
    // ------------------------------------------------------------------

    public UUID getOrganizationId()   { return organizationId; }
    public String getName()           { return name; }
    public Gender getGender()         { return gender; }
    public String getSpeciality()     { return speciality; }
    public Integer getEncounters()    { return encounters; }
    public Integer getProcedures()    { return procedures; }
    public UUID getAuthId()           { return authId; }
    public String getProviderCode()   { return providerCode; }
    public String getPhone()          { return phone; }
    public String getLicenseNumber()  { return licenseNumber; }
    public String getNpi()            { return npi; }
    public Boolean getIsActive()      { return isActive; }
    public String getBio()            { return bio; }
    public Organization getOrganization() { return organization; }
    public User getUser()             { return user; }

    // ------------------------------------------------------------------
    // Setters
    // authId     — set only via linkAuthAccount(), no direct setter
    // providerCode — set by DB sequence, no setter
    // ------------------------------------------------------------------

    public void setName(String name) {
        this.name = ValidationUtils.validateAndNormalizeString(
                name, FIELD_PROVIDER_NAME, ValidationConstants.MAX_FULL_NAME_LENGTH);
    }

    public void setGender(Gender gender)           { this.gender = gender; }
    public void setSpeciality(String speciality)   { this.speciality = speciality; }
    public void setEncounters(Integer encounters)  { this.encounters = encounters; }
    public void setProcedures(Integer procedures)  { this.procedures = procedures; }

    public void setPhone(String phone) {
        this.phone = ValidationUtils.validateAndNormalizeString(
                phone, FIELD_PHONE,
                ValidationConstants.MAX_PHONE_LENGTH,
                ValidationPatterns.PHONE,
               FIELD_PHONE +  " must be a valid international format");
    }

    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = ValidationUtils.validateAndNormalizeString(
                licenseNumber, FIELD_LICENSE_NUMBER, DatabaseConstants.LEN_LICENSE_NUMBER);
    }

    public void setNpi(String npi) {
        this.npi = npi;
    }

    public void setIsActive(Boolean isActive) {
        if (isActive == null)
            throw new ValidationException("isActive cannot be null");
        this.isActive = isActive;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }
}