apiVersion: v1
kind: Namespace
metadata:
  name: health-ai
  labels:
    name: health-ai
    environment: gke
    app: health-ai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: health-ai-sa
  namespace: health-ai
  labels:
    app: health-ai
