# Cloud Run Configuration for Gateway Service
# Design Phase Only - Basic Structure

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gateway-service
spec:
  template:
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/gateway-service:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        # Environment variables will be configured during implementation
