spring:
  datasource:
    url: "jdbc:postgresql://ep-rough-sun-a5xq8x2p.us-east-2.aws.neon.tech:5432/neondb?sslmode=require&ssl=true&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory"
    username: neondb_owner
    password: pg_mNa1rdsbhP7V
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

logging:
  level:
    com.healthcare: INFO