spring:
  datasource:
    url: "jdbc:postgresql://vohmpqlyiqysdtvzccnz.supabase.co:443/postgres?sslmode=require"
    username: postgres
    password: cloudP2025@yf
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        type:
          sql: cast
        # PostgreSQL enum handling - cast strings to enum types
        jdbc:
          time_zone: UTC
        # Enable PostgreSQL enum support
        connection:
          provider_disables_autocommit: true

logging:
  level:
    com.healthcare: INFO