spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://db.dummy-project-ref.supabase.co:5432/postgres?sslmode=require&connectTimeout=60000&socketTimeout=60000&loginTimeout=60000}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:dummy-password-123}"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        type:
          sql: cast
        # PostgreSQL enum handling - cast strings to enum types
        jdbc:
          time_zone: UTC
        # Enable PostgreSQL enum support
        connection:
          provider_disables_autocommit: true

logging:
  level:
    com.healthcare: INFO